import { ASSET_BLUE_PALETTE, ENERGY_FLOW_COLORS } from "../../shared";
import type { AssetChartSeries } from "../../shared";
import type {
  BatteryAggregation,
  BatteryChartSeries,
  BatteryEnergySeriesKey,
  BatteryTimeView,
} from "../types/battery-types";

export const BATTERY_DEFAULT_SELECTION = {
  timeView: "year",
  aggregation: "combined",
  breakdown: false,
} as const satisfies {
  timeView: BatteryTimeView;
  aggregation: BatteryAggregation;
  breakdown: boolean;
};

export const COMBINED_BATTERY_SERIES: readonly AssetChartSeries<BatteryEnergySeriesKey>[] = [
  {
    key: "batteryImport",
    label: "Battery Import",
    color: ASSET_BLUE_PALETTE.dark,
    stackId: "battery",
  },
  {
    key: "batteryExport",
    label: "Battery Export",
    color: ASSET_BLUE_PALETTE.light,
    stackId: "battery",
  },
];

export const BREAKDOWN_BATTERY_SERIES: readonly AssetChartSeries<BatteryEnergySeriesKey>[] = [
  {
    key: "gridToBattery",
    label: "Grid → Battery",
    color: ASSET_BLUE_PALETTE.dark,
    stackId: "battery",
    stackPosition: "bottom",
  },
  {
    key: "solarToBattery",
    label: "Solar → Battery",
    color: ENERGY_FLOW_COLORS.solarProduction,
    stackId: "battery",
    stackPosition: "top",
  },
  {
    key: "batteryToGrid",
    label: "Battery → Grid",
    color: ENERGY_FLOW_COLORS.gridBatteryToGrid,
    stackId: "battery",
    stackPosition: "bottom",
  },
  {
    key: "batteryToCharger",
    label: "Battery → Charger",
    color: ENERGY_FLOW_COLORS.toCharger,
    stackId: "battery",
  },
  {
    key: "batteryToOwnUse",
    label: "Battery → Own Use",
    color: ENERGY_FLOW_COLORS.ownUse,
    stackId: "battery",
    stackPosition: "top",
  },
];

export const BATTERY_PROFIT_SERIES: BatteryChartSeries = {
  key: "cumulativeProfit",
  label: "Profit",
  color: "#15803d",
  kind: "line",
  yAxisId: "right",
  strokeDasharray: "7 5",
};

export const BATTERY_TOOLTIP_DESCRIPTIONS = {
  profit:
    "Net financial value created by the battery over the selected period. Profit equals revenue plus savings minus grid charging costs.",
  compactProfit:
    "Net financial value created by the battery. Profit equals revenue plus savings minus grid charging costs.",
  revenue: "Income generated by exporting battery energy to the electricity grid.",
  savings:
    "Money saved because the battery supplied EV charging or local electricity use instead of purchasing that energy directly from the grid.",
  costs:
    "Electricity purchase costs for charging the battery from the grid. Energy charged from solar is excluded because it has no electricity purchase cost.",
  solarCharging:
    "Solar energy supplied to the battery has an electricity purchase cost of €0 and is therefore not included in grid charging costs.",
} as const;
